version: "3"
services:
  mysql:
    image: mysql:8-oracle
    env_file:
      - .env
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: